set number
syntax on
set showcmd
set mouse=a
set showmode
set encoding=utf-8
set t_Co=256
filetype indent on
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set relativenumber
set wrap
set laststatus=2
set ruler
set showmatch
set hlsearch
set incsearch
set ignorecase
set smartcase
set autochdir
set autoread
set wildmenu
set wildmode=longest:list,full
set noerrorbells
set bg=dark
colorscheme retrobox
